name: Node

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: pnpm/action-setup@v2
      with:
        version: '^6.10'

    - uses: actions/setup-node@v2
      with:
        node-version: 'lts'
        cache: 'pnpm'

    - uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '6.2'

    - run: pnpm i
    - run: pnpm recursive test
